#define uS_TO_S_FACTOR 1000000  /* Conversion factor for micro seconds to seconds */
int polling_rate = 5000;
int send_info_rate = 10000;
unsigned long currentMillis = 0;
unsigned long last_poll_Millis = 0;
unsigned long last_info_Millis = 0;

const char* ssid = "";
const char* password = "";
WiFiClient espClient;
WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP, "", -18000, 60000);

PubSubClient mqtt_client(espClient);
// MQTT Config
const char *mqttServerIp = "";
const short mqttServerPort = 1883;
const char *mqttUsername = "";
const char *mqttPassword = "";
// Only change ClientName
#define ClientName ""
/// the following topics are generated by preprocessor using the client name
const char *mqttClientName = ClientName;
const char *water_level_topic = ClientName "/json";
const char *mqtt_log_topic = ClientName "/logs";
const char *mqtt_response_topic = ClientName "/response";
const char *json_command_topic = ClientName "/command";
const char *mqtt_info_topic = ClientName "/info";
const char *willTopic = ClientName "/status";
/// You can modify after this
const char *willMessage = "Offline";

int willQoS = 1;
int willRetain = 1;
bool woke_from_sleep;
char ip_char[15];

int mqtt_failed_connection_attempts;
int willQoS = 1;
boolean willRetain = 1;
PubSubClient mqtt_client(espClient);
bool wasConnected = 0;

char ip_char[15];
IPAddress ip = WiFi.localIP();
sprintf(ip_char, "%d.%d.%d.%d", ip[0], ip[1], ip[2], ip[3]);


//
///........ You have to choose which sensor you used.
// #define BME_enable
// #define BMP_enable
// #define DS18_enable
#define AHTx_enable
